/* Auto-generated by genmsg_cpp for file /home/joaoquintas/ros_workspace/SRC/auction_methods_stack/auction_msgs/msg/Auction.msg */
#ifndef AUCTION_MSGS_MESSAGE_AUCTION_H
#define AUCTION_MSGS_MESSAGE_AUCTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"

namespace auction_msgs
{
template <class ContainerAllocator>
struct Auction_ {
  typedef Auction_<ContainerAllocator> Type;

  Auction_()
  : header()
  , command()
  , task_type_name()
  , subject()
  , metrics()
  , length()
  , task_location()
  {
  }

  Auction_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , command(_alloc)
  , task_type_name(_alloc)
  , subject(_alloc)
  , metrics(_alloc)
  , length()
  , task_location(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  command;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_type_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  task_type_name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _subject_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  subject;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _metrics_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  metrics;

  typedef ros::Duration _length_type;
  ros::Duration length;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _task_location_type;
   ::geometry_msgs::Point_<ContainerAllocator>  task_location;


private:
  static const char* __s_getDataType_() { return "auction_msgs/Auction"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "003387503e87218848189bfdbbf986d1"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
string command\n\
string task_type_name\n\
string subject\n\
string metrics\n\
duration length\n\
geometry_msgs/Point task_location\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, command);
    ros::serialization::serialize(stream, task_type_name);
    ros::serialization::serialize(stream, subject);
    ros::serialization::serialize(stream, metrics);
    ros::serialization::serialize(stream, length);
    ros::serialization::serialize(stream, task_location);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, command);
    ros::serialization::deserialize(stream, task_type_name);
    ros::serialization::deserialize(stream, subject);
    ros::serialization::deserialize(stream, metrics);
    ros::serialization::deserialize(stream, length);
    ros::serialization::deserialize(stream, task_location);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(command);
    size += ros::serialization::serializationLength(task_type_name);
    size += ros::serialization::serializationLength(subject);
    size += ros::serialization::serializationLength(metrics);
    size += ros::serialization::serializationLength(length);
    size += ros::serialization::serializationLength(task_location);
    return size;
  }

  typedef boost::shared_ptr< ::auction_msgs::Auction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auction_msgs::Auction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Auction
typedef  ::auction_msgs::Auction_<std::allocator<void> > Auction;

typedef boost::shared_ptr< ::auction_msgs::Auction> AuctionPtr;
typedef boost::shared_ptr< ::auction_msgs::Auction const> AuctionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::auction_msgs::Auction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::auction_msgs::Auction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace auction_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::auction_msgs::Auction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::auction_msgs::Auction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::auction_msgs::Auction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "003387503e87218848189bfdbbf986d1";
  }

  static const char* value(const  ::auction_msgs::Auction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x003387503e872188ULL;
  static const uint64_t static_value2 = 0x48189bfdbbf986d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::auction_msgs::Auction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_msgs/Auction";
  }

  static const char* value(const  ::auction_msgs::Auction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::auction_msgs::Auction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string command\n\
string task_type_name\n\
string subject\n\
string metrics\n\
duration length\n\
geometry_msgs/Point task_location\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::auction_msgs::Auction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::auction_msgs::Auction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::auction_msgs::Auction_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::auction_msgs::Auction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.command);
    stream.next(m.task_type_name);
    stream.next(m.subject);
    stream.next(m.metrics);
    stream.next(m.length);
    stream.next(m.task_location);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Auction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auction_msgs::Auction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::auction_msgs::Auction_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "task_type_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_type_name);
    s << indent << "subject: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.subject);
    s << indent << "metrics: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.metrics);
    s << indent << "length: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.length);
    s << indent << "task_location: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.task_location);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AUCTION_MSGS_MESSAGE_AUCTION_H

