/* Auto-generated by genmsg_cpp for file /home/joaoquintas/ros_workspace/SRC/auction_methods_stack/auction_msgs/msg/Bid.msg */
#ifndef AUCTION_MSGS_MESSAGE_BID_H
#define AUCTION_MSGS_MESSAGE_BID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace auction_msgs
{
template <class ContainerAllocator>
struct Bid_ {
  typedef Bid_<ContainerAllocator> Type;

  Bid_()
  : header()
  , buyer_id()
  , cost_distance(0)
  {
  }

  Bid_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , buyer_id(_alloc)
  , cost_distance(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _buyer_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  buyer_id;

  typedef int64_t _cost_distance_type;
  int64_t cost_distance;


private:
  static const char* __s_getDataType_() { return "auction_msgs/Bid"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a9fd8c7cc5d27c4274d3730239f98aaf"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
string buyer_id\n\
int64 cost_distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, buyer_id);
    ros::serialization::serialize(stream, cost_distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, buyer_id);
    ros::serialization::deserialize(stream, cost_distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(buyer_id);
    size += ros::serialization::serializationLength(cost_distance);
    return size;
  }

  typedef boost::shared_ptr< ::auction_msgs::Bid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auction_msgs::Bid_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Bid
typedef  ::auction_msgs::Bid_<std::allocator<void> > Bid;

typedef boost::shared_ptr< ::auction_msgs::Bid> BidPtr;
typedef boost::shared_ptr< ::auction_msgs::Bid const> BidConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::auction_msgs::Bid_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::auction_msgs::Bid_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace auction_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::auction_msgs::Bid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::auction_msgs::Bid_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::auction_msgs::Bid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a9fd8c7cc5d27c4274d3730239f98aaf";
  }

  static const char* value(const  ::auction_msgs::Bid_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa9fd8c7cc5d27c42ULL;
  static const uint64_t static_value2 = 0x74d3730239f98aafULL;
};

template<class ContainerAllocator>
struct DataType< ::auction_msgs::Bid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_msgs/Bid";
  }

  static const char* value(const  ::auction_msgs::Bid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::auction_msgs::Bid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string buyer_id\n\
int64 cost_distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::auction_msgs::Bid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::auction_msgs::Bid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::auction_msgs::Bid_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::auction_msgs::Bid_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.buyer_id);
    stream.next(m.cost_distance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Bid_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auction_msgs::Bid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::auction_msgs::Bid_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "buyer_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.buyer_id);
    s << indent << "cost_distance: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cost_distance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AUCTION_MSGS_MESSAGE_BID_H

