/* Auto-generated by genmsg_cpp for file /home/joaoquintas/ros_workspace/SRC/auction_methods_stack/auction_srvs/srv/AuctionService.srv */
#ifndef AUCTION_SRVS_SERVICE_AUCTIONSERVICE_H
#define AUCTION_SRVS_SERVICE_AUCTIONSERVICE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "auction_msgs/Auction.h"


#include "auction_msgs/Bid.h"

namespace auction_srvs
{
template <class ContainerAllocator>
struct AuctionServiceRequest_ {
  typedef AuctionServiceRequest_<ContainerAllocator> Type;

  AuctionServiceRequest_()
  : role()
  , auction_type()
  , sending_node()
  , nodes_collected()
  , auction_data()
  {
  }

  AuctionServiceRequest_(const ContainerAllocator& _alloc)
  : role(_alloc)
  , auction_type(_alloc)
  , sending_node(_alloc)
  , nodes_collected(_alloc)
  , auction_data(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _role_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  role;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _auction_type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  auction_type;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sending_node_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  sending_node;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nodes_collected_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  nodes_collected;

  typedef  ::auction_msgs::Auction_<ContainerAllocator>  _auction_data_type;
   ::auction_msgs::Auction_<ContainerAllocator>  auction_data;


private:
  static const char* __s_getDataType_() { return "auction_srvs/AuctionServiceRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "71cdc8b8f8b1a628ff5e78f4bb4202a8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d6b81557d076b0cba63ad79512801bd6"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
\n\
string role\n\
string auction_type\n\
string sending_node\n\
string nodes_collected\n\
auction_msgs/Auction auction_data\n\
\n\
\n\
================================================================================\n\
MSG: auction_msgs/Auction\n\
Header header\n\
string command\n\
string task_type_name\n\
string subject\n\
string metrics\n\
duration length\n\
geometry_msgs/Point task_location\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, role);
    ros::serialization::serialize(stream, auction_type);
    ros::serialization::serialize(stream, sending_node);
    ros::serialization::serialize(stream, nodes_collected);
    ros::serialization::serialize(stream, auction_data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, role);
    ros::serialization::deserialize(stream, auction_type);
    ros::serialization::deserialize(stream, sending_node);
    ros::serialization::deserialize(stream, nodes_collected);
    ros::serialization::deserialize(stream, auction_data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(role);
    size += ros::serialization::serializationLength(auction_type);
    size += ros::serialization::serializationLength(sending_node);
    size += ros::serialization::serializationLength(nodes_collected);
    size += ros::serialization::serializationLength(auction_data);
    return size;
  }

  typedef boost::shared_ptr< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AuctionServiceRequest
typedef  ::auction_srvs::AuctionServiceRequest_<std::allocator<void> > AuctionServiceRequest;

typedef boost::shared_ptr< ::auction_srvs::AuctionServiceRequest> AuctionServiceRequestPtr;
typedef boost::shared_ptr< ::auction_srvs::AuctionServiceRequest const> AuctionServiceRequestConstPtr;


template <class ContainerAllocator>
struct AuctionServiceResponse_ {
  typedef AuctionServiceResponse_<ContainerAllocator> Type;

  AuctionServiceResponse_()
  : response_info()
  , bid_data()
  {
  }

  AuctionServiceResponse_(const ContainerAllocator& _alloc)
  : response_info(_alloc)
  , bid_data(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_info_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  response_info;

  typedef  ::auction_msgs::Bid_<ContainerAllocator>  _bid_data_type;
   ::auction_msgs::Bid_<ContainerAllocator>  bid_data;


private:
  static const char* __s_getDataType_() { return "auction_srvs/AuctionServiceResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "60191484f19ef1e101f27cfcfa9ff2c2"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d6b81557d076b0cba63ad79512801bd6"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
\n\
string response_info\n\
auction_msgs/Bid bid_data\n\
\n\
================================================================================\n\
MSG: auction_msgs/Bid\n\
Header header\n\
string buyer_id\n\
int64 cost_distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, response_info);
    ros::serialization::serialize(stream, bid_data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, response_info);
    ros::serialization::deserialize(stream, bid_data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(response_info);
    size += ros::serialization::serializationLength(bid_data);
    return size;
  }

  typedef boost::shared_ptr< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AuctionServiceResponse
typedef  ::auction_srvs::AuctionServiceResponse_<std::allocator<void> > AuctionServiceResponse;

typedef boost::shared_ptr< ::auction_srvs::AuctionServiceResponse> AuctionServiceResponsePtr;
typedef boost::shared_ptr< ::auction_srvs::AuctionServiceResponse const> AuctionServiceResponseConstPtr;

struct AuctionService
{

typedef AuctionServiceRequest Request;
typedef AuctionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct AuctionService
} // namespace auction_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "71cdc8b8f8b1a628ff5e78f4bb4202a8";
  }

  static const char* value(const  ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x71cdc8b8f8b1a628ULL;
  static const uint64_t static_value2 = 0xff5e78f4bb4202a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctionServiceRequest";
  }

  static const char* value(const  ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
string role\n\
string auction_type\n\
string sending_node\n\
string nodes_collected\n\
auction_msgs/Auction auction_data\n\
\n\
\n\
================================================================================\n\
MSG: auction_msgs/Auction\n\
Header header\n\
string command\n\
string task_type_name\n\
string subject\n\
string metrics\n\
duration length\n\
geometry_msgs/Point task_location\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "60191484f19ef1e101f27cfcfa9ff2c2";
  }

  static const char* value(const  ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x60191484f19ef1e1ULL;
  static const uint64_t static_value2 = 0x01f27cfcfa9ff2c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctionServiceResponse";
  }

  static const char* value(const  ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
string response_info\n\
auction_msgs/Bid bid_data\n\
\n\
================================================================================\n\
MSG: auction_msgs/Bid\n\
Header header\n\
string buyer_id\n\
int64 cost_distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::auction_srvs::AuctionServiceRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.role);
    stream.next(m.auction_type);
    stream.next(m.sending_node);
    stream.next(m.nodes_collected);
    stream.next(m.auction_data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AuctionServiceRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::auction_srvs::AuctionServiceResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.response_info);
    stream.next(m.bid_data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AuctionServiceResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<auction_srvs::AuctionService> {
  static const char* value() 
  {
    return "d6b81557d076b0cba63ad79512801bd6";
  }

  static const char* value(const auction_srvs::AuctionService&) { return value(); } 
};

template<>
struct DataType<auction_srvs::AuctionService> {
  static const char* value() 
  {
    return "auction_srvs/AuctionService";
  }

  static const char* value(const auction_srvs::AuctionService&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<auction_srvs::AuctionServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d6b81557d076b0cba63ad79512801bd6";
  }

  static const char* value(const auction_srvs::AuctionServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<auction_srvs::AuctionServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctionService";
  }

  static const char* value(const auction_srvs::AuctionServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<auction_srvs::AuctionServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d6b81557d076b0cba63ad79512801bd6";
  }

  static const char* value(const auction_srvs::AuctionServiceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<auction_srvs::AuctionServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctionService";
  }

  static const char* value(const auction_srvs::AuctionServiceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AUCTION_SRVS_SERVICE_AUCTIONSERVICE_H

