/* Auto-generated by genmsg_cpp for file /home/joaoquintas/ros_workspace/SRC/auction_methods_stack/auction_srvs/srv/AuctioneerService.srv */
#ifndef AUCTION_SRVS_SERVICE_AUCTIONEERSERVICE_H
#define AUCTION_SRVS_SERVICE_AUCTIONEERSERVICE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "auction_msgs/Auction.h"



namespace auction_srvs
{
template <class ContainerAllocator>
struct AuctioneerServiceRequest_ {
  typedef AuctioneerServiceRequest_<ContainerAllocator> Type;

  AuctioneerServiceRequest_()
  : sending_node()
  , nodes_collected()
  , auction_data()
  {
  }

  AuctioneerServiceRequest_(const ContainerAllocator& _alloc)
  : sending_node(_alloc)
  , nodes_collected(_alloc)
  , auction_data(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sending_node_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  sending_node;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nodes_collected_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  nodes_collected;

  typedef  ::auction_msgs::Auction_<ContainerAllocator>  _auction_data_type;
   ::auction_msgs::Auction_<ContainerAllocator>  auction_data;


private:
  static const char* __s_getDataType_() { return "auction_srvs/AuctioneerServiceRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c7bf0ccec44590484a6687d32dad126a"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c2995a3b557484c55996e3115ca3226e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
\n\
string sending_node\n\
string nodes_collected\n\
auction_msgs/Auction auction_data\n\
\n\
\n\
================================================================================\n\
MSG: auction_msgs/Auction\n\
Header header\n\
string command\n\
string task_type_name\n\
string subject\n\
string metrics\n\
duration length\n\
geometry_msgs/Point task_location\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, sending_node);
    ros::serialization::serialize(stream, nodes_collected);
    ros::serialization::serialize(stream, auction_data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, sending_node);
    ros::serialization::deserialize(stream, nodes_collected);
    ros::serialization::deserialize(stream, auction_data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(sending_node);
    size += ros::serialization::serializationLength(nodes_collected);
    size += ros::serialization::serializationLength(auction_data);
    return size;
  }

  typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AuctioneerServiceRequest
typedef  ::auction_srvs::AuctioneerServiceRequest_<std::allocator<void> > AuctioneerServiceRequest;

typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceRequest> AuctioneerServiceRequestPtr;
typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceRequest const> AuctioneerServiceRequestConstPtr;


template <class ContainerAllocator>
struct AuctioneerServiceResponse_ {
  typedef AuctioneerServiceResponse_<ContainerAllocator> Type;

  AuctioneerServiceResponse_()
  : response_info()
  , winner_id()
  , winner_cost(0.0)
  {
  }

  AuctioneerServiceResponse_(const ContainerAllocator& _alloc)
  : response_info(_alloc)
  , winner_id(_alloc)
  , winner_cost(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_info_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  response_info;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _winner_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  winner_id;

  typedef double _winner_cost_type;
  double winner_cost;


private:
  static const char* __s_getDataType_() { return "auction_srvs/AuctioneerServiceResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "86ae97f3885efd6c482c364225af8d5b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c2995a3b557484c55996e3115ca3226e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
\n\
string response_info\n\
string winner_id\n\
float64 winner_cost\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, response_info);
    ros::serialization::serialize(stream, winner_id);
    ros::serialization::serialize(stream, winner_cost);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, response_info);
    ros::serialization::deserialize(stream, winner_id);
    ros::serialization::deserialize(stream, winner_cost);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(response_info);
    size += ros::serialization::serializationLength(winner_id);
    size += ros::serialization::serializationLength(winner_cost);
    return size;
  }

  typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AuctioneerServiceResponse
typedef  ::auction_srvs::AuctioneerServiceResponse_<std::allocator<void> > AuctioneerServiceResponse;

typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceResponse> AuctioneerServiceResponsePtr;
typedef boost::shared_ptr< ::auction_srvs::AuctioneerServiceResponse const> AuctioneerServiceResponseConstPtr;

struct AuctioneerService
{

typedef AuctioneerServiceRequest Request;
typedef AuctioneerServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct AuctioneerService
} // namespace auction_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c7bf0ccec44590484a6687d32dad126a";
  }

  static const char* value(const  ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc7bf0ccec4459048ULL;
  static const uint64_t static_value2 = 0x4a6687d32dad126aULL;
};

template<class ContainerAllocator>
struct DataType< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctioneerServiceRequest";
  }

  static const char* value(const  ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
string sending_node\n\
string nodes_collected\n\
auction_msgs/Auction auction_data\n\
\n\
\n\
================================================================================\n\
MSG: auction_msgs/Auction\n\
Header header\n\
string command\n\
string task_type_name\n\
string subject\n\
string metrics\n\
duration length\n\
geometry_msgs/Point task_location\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "86ae97f3885efd6c482c364225af8d5b";
  }

  static const char* value(const  ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x86ae97f3885efd6cULL;
  static const uint64_t static_value2 = 0x482c364225af8d5bULL;
};

template<class ContainerAllocator>
struct DataType< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctioneerServiceResponse";
  }

  static const char* value(const  ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
string response_info\n\
string winner_id\n\
float64 winner_cost\n\
\n\
";
  }

  static const char* value(const  ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.sending_node);
    stream.next(m.nodes_collected);
    stream.next(m.auction_data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AuctioneerServiceRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.response_info);
    stream.next(m.winner_id);
    stream.next(m.winner_cost);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AuctioneerServiceResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<auction_srvs::AuctioneerService> {
  static const char* value() 
  {
    return "c2995a3b557484c55996e3115ca3226e";
  }

  static const char* value(const auction_srvs::AuctioneerService&) { return value(); } 
};

template<>
struct DataType<auction_srvs::AuctioneerService> {
  static const char* value() 
  {
    return "auction_srvs/AuctioneerService";
  }

  static const char* value(const auction_srvs::AuctioneerService&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c2995a3b557484c55996e3115ca3226e";
  }

  static const char* value(const auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctioneerService";
  }

  static const char* value(const auction_srvs::AuctioneerServiceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c2995a3b557484c55996e3115ca3226e";
  }

  static const char* value(const auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "auction_srvs/AuctioneerService";
  }

  static const char* value(const auction_srvs::AuctioneerServiceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AUCTION_SRVS_SERVICE_AUCTIONEERSERVICE_H

